# Clases 2-3: Sistemas de Generadores, Independencia Lineal y Transformaciones Lineales

En esta notebook, exploraremos conceptos fundamentales de álgebra lineal que son esenciales para el estudio de espacios vectoriales y transformaciones lineales. Estos conceptos incluyen sistemas de generadores, independencia lineal, bases, y dimensiones de subespacios. Además, implementaremos ejemplos prácticos para entender cómo aplicar estos conceptos en problemas específicos.

## Objetivos de Aprendizaje

- Comprender y definir sistemas de generadores y su importancia.
- Explorar el concepto de independencia lineal y cómo determinar si un conjunto de vectores es independiente.
- Identificar bases y calcular la dimensión de subespacios.
- Implementar ejemplos prácticos para solidificar la comprensión de estos conceptos.

## Sistemas de Generadores

Un **sistema de generadores** de un espacio vectorial es un conjunto de vectores en dicho espacio tal que cualquier vector del espacio se puede expresar como combinación lineal de los vectores del sistema. Si un espacio vectorial tiene un sistema de generadores finito, se dice que es finitamente generado.

### Propiedades Clave:
- **Generadores Mínimos**: El conjunto más pequeño de vectores que aún genera todo el espacio.
- **Espacio Generado**: El conjunto de todas las combinaciones lineales posibles de los vectores generadores.

## Independencia Lineal

Un conjunto de vectores es **independiente linealmente** si ninguno de los vectores en el conjunto puede ser expresado como una combinación lineal de los otros vectores. Este concepto es crucial para determinar las bases de un espacio vectorial.

### Características de la Independencia Lineal:
- Si un conjunto de vectores es linealmente independiente, entonces ningún vector en el conjunto puede ser removido sin cambiar el espacio generado por el conjunto.
- La independencia lineal de un conjunto de vectores se puede verificar usando el determinante (en el caso de matrices cuadradas) o más generalmente, reduciendo la matriz que forman los vectores a su forma escalonada reducida.

## Bases y Dimensión

Una **base** de un espacio vectorial es un conjunto de vectores que es tanto generador como linealmente independiente. La **dimensión** de un espacio vectorial es el número de vectores en cualquier base del espacio, lo que también refleja el número mínimo de coordenadas necesarias para describir cualquier vector en ese espacio.

### Ejemplo Práctico: Sistema de Generadores para Matrices 2x2

A continuación, vamos a implementar y verificar un sistema de generadores para el espacio de todas las matrices 2x2.


In [1]:

import numpy as np

def sistema_generadores():
    generadores = [
        np.array([[1, 0], [0, 0]]),
        np.array([[0, 1], [0, 0]]),
        np.array([[0, 0], [1, 0]]),
        np.array([[0, 0], [0, 1]])
    ]
    return generadores

print("Sistema de generadores para matrices 2x2:")
for g in sistema_generadores():
    print(g)

Sistema de generadores para matrices 2x2:
[[1 0]
 [0 0]]
[[0 1]
 [0 0]]
[[0 0]
 [1 0]]
[[0 0]
 [0 1]]


## Discusión

En el código anterior, definimos un sistema de generadores para el espacio de todas las matrices 2x2. Cada matriz generadora tiene un único elemento no nulo, ubicado en una de las cuatro posiciones posibles de una matriz 2x2. Este sistema es efectivamente una base, ya que las matrices son linealmente independientes y cualquier matriz 2x2 puede ser expresada como una combinación lineal de estas.

### Ejercicios Adicionales

1. **Verificar la Independencia Lineal**: Escribe un código que verifique si el conjunto de matrices generadoras definido es linealmente independiente.

2. **Explorar Subespacios**: Considera subconjuntos de las matrices generadoras y determina si forman una base para algún subespacio de las matrices 2x2. Por ejemplo, considera el subconjunto de matrices que solo 

3. **Dimensiones y Subespacios**: Calcula la dimensión de diferentes subespacios generados por subconjuntos de las matrices generadoras, como el espacio de matrices diagonales o el de matrices simétricas.tienen componentes no nulos en la primera fila.

Estos ejercicios ayudarán a profundizar tu comprensión de los conceptos de sistemas de generadores, independencia lineal y dimensiones de subespacios.

In [2]:

# Importamos las librerías necesarias
import numpy as np
import sympy as sp

# Definimos las funciones para mostrar los generadores de cada caso
def mostrar_generadores_a():
    generadores_a = [
        [1, 1, 0],
        [0, 1, 1]
    ]
    print("Sistema de generadores para (a):", generadores_a)

def mostrar_generadores_b():
    generadores_b = [
        np.array([[0, 1j, 0], [-1j, 0, 0], [0, 0, 0]]),
        np.array([[0, 0, 1j], [0, 0, 0], [-1j, 0, 0]]),
        np.array([[0, 0, 0], [0, 0, 1j], [0, -1j, 0]])
    ]
    print("Sistema de generadores para (b):")
    for g in generadores_b:
        print(g)


In [3]:

# Ejecutamos las funciones para mostrar los generadores
mostrar_generadores_a()
mostrar_generadores_b()


Sistema de generadores para (a): [[1, 1, 0], [0, 1, 1]]
Sistema de generadores para (b):
[[ 0.+0.j  0.+1.j  0.+0.j]
 [-0.-1.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j]]
[[ 0.+0.j  0.+0.j  0.+1.j]
 [ 0.+0.j  0.+0.j  0.+0.j]
 [-0.-1.j  0.+0.j  0.+0.j]]
[[ 0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+1.j]
 [ 0.+0.j -0.-1.j  0.+0.j]]


In [4]:

def mostrar_generadores_c():
    generadores_c = [
        np.array([[1, 0, 0], [0, -1, 0], [0, 0, 0]]),
        np.array([[0, 1, 0], [0, 0, 0], [0, 0, -1]]),
        np.array([[0, 0, 1], [0, 0, 0], [0, -1, 0]])
    ]
    print("Sistema de generadores para (c):")
    for g in generadores_c:
        print(g)

def mostrar_generadores_d():
    generadores_d = [
        [1, -1, 0, 0],
        [0, 1, -1-complex(0,1), complex(0,1)]
    ]
    print("Sistema de generadores para (d):", generadores_d)



In [5]:

mostrar_generadores_c()
mostrar_generadores_d()

Sistema de generadores para (c):
[[ 1  0  0]
 [ 0 -1  0]
 [ 0  0  0]]
[[ 0  1  0]
 [ 0  0  0]
 [ 0  0 -1]]
[[ 0  0  1]
 [ 0  0  0]
 [ 0 -1  0]]
Sistema de generadores para (d): [[1, -1, 0, 0], [0, 1, (-1-1j), 1j]]


### Discusión y Ejercicios Adicionales

En este ejercicio, hemos explorado cómo encontrar sistemas de generadores para diferentes conjuntos de vectores y matrices bajo ciertas condiciones. Para cada caso, hemos utilizado la teoría de álgebra lineal para establecer un conjunto de generadores que satisfacen las condiciones dadas.

**Ejercicios adicionales:**
1. Verifica que cada uno de los sistemas de generadores propuestos realmente genera el espacio vectorial o conjunto de matrices descrito.
2. Explora la posibilidad de reducir aún más el número de generadores en cada caso, si es posible.
3. Generaliza el problema (b) para matrices de tamaño \( n \times n \) y encuentra un sistema de generadores para matrices antisimétricas en dimensiones superiores.


In [6]:

# Importamos las librerías necesarias para el manejo de matrices
import numpy as np

def es_linealmente_independiente(vectores):
    """
    Esta función verifica si un conjunto dado de vectores es linealmente independiente.
    
    Args:
    vectores (list of lists): Lista de vectores en ${\mathbb R^m}$.
    
    Returns:
    bool: True si los vectores son linealmente independientes, False en caso contrario.
    """
    # Convertimos la lista de vectores en una matriz de numpy
    matriz = np.array(vectores).T
    
    # Comprobamos la independencia lineal verificando si el rango de la matriz es igual al número de vectores
    return np.linalg.matrix_rank(matriz) == len(vectores)

# Definimos un conjunto de vectores en R^3
vectores = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
]

# Llamamos a la función y mostramos el resultado
print("¿Son linealmente independientes?", es_linealmente_independiente(vectores))


¿Son linealmente independientes? True


### Discusión y Ejercicios Adicionales

La función `es_linealmente_independiente` utiliza el rango de la matriz formada por los vectores proporcionados para determinar si son linealmente independientes. Esta técnica es eficaz y se basa en el principio de que los vectores son independientes si y solo si el rango de la matriz es igual al número de vectores.

**Ejercicios adicionales:**

1. **Modificar Vectores**: Cambia los vectores en el ejemplo y verifica si siguen siendo linealmente independientes. Por ejemplo, prueba con vectores que sabes que son dependientes, como `[[1, 0, 0], [2, 0, 0], [3, 0, 0]]`.

2. **Vectores en ${\mathbb R^4}$**: Prueba la función con vectores en ${\mathbb R^4}$ o dimensiones superiores para ver cómo se comporta con espacios de mayor dimensión.

3. **Dependencia lineal con errores**: Añade un pequeño error a vectores que son linealmente independientes (por ejemplo, sumar `0.0001` a uno de los elementos) y observa si la función todavía puede determinar correctamente su independencia.

Estos ejercicios ayudarán a explorar más a fondo el concepto de independencia lineal y cómo pequeñas modificaciones en los vectores pueden cambiar sus propiedades lineales.

# Verificación de Independencia Lineal

## Introducción Teórica

### Independencia Lineal

Un conjunto de vectores en un espacio vectorial se dice que es **independiente linealmente** si ninguno de los vectores puede ser representado como una combinación lineal de los otros. Matemáticamente, un conjunto de vectores $\{\mathbf{v}_1, \mathbf{v}_2, \dots, \mathbf{v}_n\}$ es independiente linealmente si la única solución a la ecuación:

$$
c_1 \mathbf{v}_1 + c_2 \mathbf{v}_2 + \cdots + c_n \mathbf{v}_n = \mathbf{0}
$$

es $c_1 = c_2 = \cdots = c_n = 0$.

### Verificación de Independencia Lineal

Para verificar la independencia lineal de un conjunto de vectores, podemos utilizar métodos algebraicos como la **eliminación Gaussiana** y la **descomposición en valores singulares (SVD)**. Estos métodos nos permiten determinar el rango de la matriz formada por estos vectores como columnas. Si el rango de la matriz es igual al número de vectores, entonces el conjunto es independiente linealmente.

### Métodos de Verificación

#### Eliminación Gaussiana

La eliminación gaussiana transforma una matriz en su forma escalonada reducida por filas mediante operaciones elementales de fila. El número de filas no nulas en esta forma escalonada es el rango de la matriz. La complejidad temporal de este método es $\mathcal{O}(\frac{2}{3} mn^2)$, donde $m$ es el número de filas y $n$ el número de columnas.

#### Descomposición en Valores Singulares (SVD)

SVD descompone una matriz en tres matrices, donde una de ellas contiene los valores singulares. El número de valores singulares no nulos es el rango de la matriz. Aunque computacionalmente más costosa, SVD es más estable numéricamente y es el método preferido en bibliotecas modernas como NumPy.

## Implementación y Comparación de Métodos


In [1]:
## Trabajar sobre el codigo de ejemplo...
import numpy as np

# Método usando Eliminación Gaussiana
def verificar_independencia_gauss(vectores):
    matriz = np.array(vectores).T
    # Reducir la matriz a su forma escalonada (row echelon form)
    rref = np.linalg.matrix_rank(matriz)
    return rref == len(vectores)

# Método usando la Descomposición en Valores Singulares (SVD)
def verificar_independencia_svd(vectores):
    matriz = np.array(vectores).T
    # Realizar la descomposición en valores singulares
    _, s, _ = np.linalg.svd(matriz)
    # Contar el número de valores singulares que no son cero (o son mayores a un umbral)
    rango = np.sum(s > 1e-10)  # Se usa un umbral para considerar valores muy pequeños como cero
    return rango == len(vectores)

vectores = [
    [1, 2, 3],
    [4, 5, 8],
    [7, 8, 9]
]

# Verificación de independencia usando ambos métodos
independencia_gauss = verificar_independencia_gauss(vectores)
independencia_svd = verificar_independencia_svd(vectores)

print(f"Independencia usando Gauss: {independencia_gauss}")
print(f"Independencia usando SVD: {independencia_svd}")

Independencia usando Gauss: True
Independencia usando SVD: True


## Discusión de Resultados

### Complejidad Temporal

- **Eliminación Gaussiana:** Tiene una complejidad temporal de $\mathcal{O}(\frac{2}{3} mn^2)$. Es eficiente para matrices con más columnas que filas, pero puede sufrir de problemas de estabilidad numérica con elementos muy grandes o muy pequeños.
- **SVD:** Aunque computacionalmente más costoso, es más robusto desde el punto de vista numérico y es el método preferido para aplicaciones prácticas, especialmente en contextos donde la precisión es crucial.

### Sugerencias para Ejercicios Adicionales

1. Experimentar con conjuntos de vectores que son independientes linealmente y comparar los resultados.
2. Analizar el impacto del tamaño de la matriz en el tiempo de cálculo para ambos métodos.
3. Investigar otros métodos de verificación de independencia lineal, como la descomposición QR.

Estos ejercicios ayudarán a profundizar la comprensión de la independencia lineal y los métodos utilizados para su verificación.

# Transformaciones Lineales y Subespacios Fundamentales

Una transformación lineal es una función entre dos espacios vectoriales que respeta las operaciones de suma de vectores y multiplicación por un escalar. Estas transformaciones son fundamentales para entender la estructura de los espacios vectoriales y tienen aplicaciones en diversas áreas como la geometría, la teoría de sistemas, la estadística, entre otras.

### Conceptos Clave:

- **Transformaciones Lineales**: Funciones que mapean un espacio vectorial en otro preservando las operaciones de suma y multiplicación por escalar.
- **Representación Matricial**: Cada transformación lineal entre espacios vectoriales finito-dimensionales puede ser representada por una matriz.
- **Subespacios Fundamentales**: Estos incluyen el núcleo y la imagen de una transformación lineal.
  - **Núcleo**: Conjunto de todos los vectores que son mapeados al vector cero.
  - **Imagen**: Conjunto de todos los vectores que resultan de aplicar la transformación.
- **Isomorfismos**: Transformaciones lineales que son biyectivas (uno a uno y sobre), indicando que el dominio y el codominio tienen la misma estructura.

### Objetivo del Laboratorio

En este laboratorio, implementaremos una transformación lineal específica y verificaremos sus propiedades utilizando Python. Esto nos ayudará a comprender cómo operan estas transformaciones y cómo podemos explorar sus subespacios fundamentales mediante programación.

Implementaremos una transformación lineal y verificaremos si satisface las propiedades de linealidad, es decir, si se preserva la suma y la multiplicación escalar.

### Definición de la Transformación Lineal

Consideremos la transformación lineal $T$ definida por:
$ T(v) = \begin{bmatrix} v_1 + v_2 \\ 2v_2 \end{bmatrix} $
donde $v = \begin{bmatrix} v_1 \\ v_2 \end{bmatrix}$ es un vector en $\mathbb{R}^2$.


### Implementación y Verificación

In [8]:

import numpy as np

def es_transformacion_lineal(T, vectores):
    # Verifica la aditividad y la homogeneidad para cada par de vectores en la lista
    return all(np.allclose(T(u + v), T(u) + T(v)) and np.allclose(T(2 * u), 2 * T(u)) for u in vectores for v in vectores)


def T(v):
    # Define la transformación lineal T
    return np.array([v[0] + v[1], 2 * v[1]])


vectores = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print("¿Es una transformación lineal?", es_transformacion_lineal(T, vectores))


¿Es una transformación lineal? True


### Discusión

El resultado de la función `es_transformacion_lineal` nos indicará si la función `T` definida es efectivamente una transformación lineal verificando las propiedades:
1. **Aditividad**: $ T(u+v) = T(u) + T(v) $
2. **Homogeneidad**: $ T(c \cdot u) = c \cdot T(u) $

### Ejercicios Adicionales

1. Modifica la transformación lineal `T` con otras funciones y verifica si siguen siendo transformaciones lineales.
2. Explora el núcleo e imagen de la transformación lineal `T` y de las modificaciones que realices.
3. Generaliza el código para verificar transformaciones lineales en $ \mathbb{R}^3 $ o espacios de mayor dimensión.


# Representación Matricial de una Transformación Lineal

Una **transformación lineal** es una función entre dos espacios vectoriales que preserva las operaciones de adición de vectores y multiplicación por un escalar. Las transformaciones lineales pueden ser representadas de manera muy conveniente y poderosa mediante matrices. Esto no solo facilita el cálculo de las transformaciones, sino que además permite la aplicación de técnicas de álgebra matricial para analizar propiedades de la transformación.

### ¿Qué es una Representación Matricial?

La representación matricial de una transformación lineal es una matriz que, al multiplicarla por un vector en el dominio de la transformación, produce el vector transformado en el codominio. La matriz de una transformación lineal depende de las bases elegidas para el dominio y el codominio.  

### Bases y Dimensiones

Una **base** de un espacio vectorial es un conjunto de vectores que son linealmente independientes y que abarcan todo el espacio. Para que una matriz represente completamente una transformación lineal, la base del espacio vectorial debe estar completamente definida.

En esta notebook, exploraremos cómo calcular la representación matricial de una transformación lineal dada una base específica.

## Ejemplo de Código

A continuación, se muestra cómo podemos definir una función en Python para calcular la representación matricial de una transformación lineal arbitraria, dada una base específica del espacio vectorial.




In [2]:
def representacion_matricial(T, base):
    """
    Calcula la matriz representativa de la transformación lineal T respecto a la base dada.
    
    Args:
    T (function): La transformación lineal a representar.
    base (list): Una lista de listas que representa los vectores base del espacio.
    
    Returns:
    numpy.ndarray: La matriz representativa de la transformación lineal.
    """
    # Aplicar T a cada vector de la base y almacenar los resultados
    transformados = [T(np.array(v)) for v in base]
    # Organizar los vectores transformados como columnas de una nueva matriz
    return np.array(transformados).T


# Definir una base estándar para R^2
base = [
    [1, 0],
    [0, 1]
]

# Definir una transformación lineal ejemplo: rotación en R^2
def T(v):
    theta = np.pi / 4  # Rotar 45 grados
    rot_matrix = np.array([
        [np.cos(theta), -np.sin(theta)],
        [np.sin(theta), np.cos(theta)]
    ])
    return rot_matrix @ v


# Calcular la matriz de la transformación
A = representacion_matricial(T, base)
print("Representación matricial de T:")
print(A/np.sqrt(2))


Representación matricial de T:
[[ 0.5 -0.5]
 [ 0.5  0.5]]


## Discusión

El código anterior define una matriz de rotación que gira vectores en el plano $\mathbb{R}^2$ por 45 grados en sentido antihorario. La función `representacion_matricial` toma esta transformación y una base, y produce la matriz que representa esta transformación en dicha base.

La salida del código será la matriz $2 \times 2$ que podemos usar para aplicar la transformación de rotación a cualquier vector en $\mathbb{R}^2$ multiplicándolo por esta matriz.

## Ejercicios Sugeridos

1. **Cambiar el Ángulo de Rotación:** Modifica el ángulo de rotación en la función `T` para ver cómo cambia la matriz resultante.
2. **Otras Transformaciones:** Implementa una transformación lineal diferente, como una dilatación o una reflexión, y calcula su matriz representativa.
3. **Diferentes Bases:** Experimenta con diferentes bases (no solo la base canónica) y observa cómo cambia la matriz de la transformación.
4. **Dimensiones Superiores:** Generaliza la función para trabajar con transformaciones en $\mathbb{R}^3$ o espacios de dimensiones superiores.

Estos ejercicios ayudarán a profundizar tu comprensión de las transformaciones lineales y su representación matricial.

# Actividad 2.7: Calcular y Visualizar el Núcleo y la Imagen de una Transformación Lineal

Una transformación lineal es una función entre dos espacios vectoriales que preserva las operaciones de adición vectorial y multiplicación escalar. Para cualquier transformación lineal, dos conceptos fundamentales son el **núcleo** y la **imagen** de la transformación.

### Núcleo (Kernel)

El núcleo de una transformación lineal $ T: V \rightarrow W $ se define como el conjunto de todos los vectores \( v \) en \( V \) tal que \( T(v) = 0 \). En términos de la matriz asociada a \( T \) respecto a alguna base, el núcleo corresponde al espacio nulo de dicha matriz. Matemáticamente, se expresa como:

$$
\text{Ker}(T) = \{ v \in V : T(v) = 0 \}
$$

### Imagen (Image)

La imagen de una transformación lineal $ T: V \rightarrow W $ es el conjunto de todos los vectores \( w \) en \( W \) que son imágenes de algún vector \( v \) en \( V \). Es equivalente al espacio columna de la matriz de \( T \) cuando se expresa en términos de una matriz respecto a bases de \( V \) y \( W \). Se expresa como:

$$
\text{Im}(T) = \{ T(v) : v \in V \}
$$

## Ejercicio Práctico

Vamos a definir una función para calcular y visualizar el núcleo y la imagen de una transformación lineal dada. Utilizaremos la descomposición en valores singulares (SVD) para obtener estas subespacios vectoriales.

Primero, definiremos la matriz de la transformación lineal \( T \) respecto a una base estándar, y luego aplicaremos las funciones para obtener el núcleo y la imagen de \( T \).


In [5]:

import numpy as np

def representacion_matricial(T, base):
    """Calcula la representación matricial de la transformación lineal T respecto a la base dada."""
    dimension = len(base)
    matriz = np.zeros((dimension, dimension))
    for i in range(dimension):
        matriz[:, i] = T(base[i])
    return matriz

def nucleo(T, base):
    """Calcula el núcleo de la transformación lineal T."""
    A = representacion_matricial(T, base)
    u, s, vh = np.linalg.svd(A)
    # El núcleo está en el último vector de vh si el valor singular correspondiente es cero
    return vh[-1] if s[-1] == 0 else np.array([])


def imagen(T, base):
    """Calcula la imagen de la transformación lineal T."""
    A = representacion_matricial(T, base)
    u, s, vh = np.linalg.svd(A)
    # La imagen está dada por las columnas de u correspondientes a valores singulares no nulos
    rank = np.linalg.matrix_rank(A)
    return u[:, :rank]


In [8]:

# Definamos la transformación lineal T
def T(v):
    # Supongamos una transformación lineal simple como un ejemplo
    return np.dot(np.array([[1, 2], [2, 4]]), v)

base = [
    [1, 0],
    [0, 1]
]

print("Núcleo de T:", nucleo(T, base))
print("Imagen de T:", imagen(T, base))

Núcleo de T: []
Imagen de T: [[-0.4472136 ]
 [-0.89442719]]


## Discusión y Conclusiones

La salida del código muestra el núcleo y la imagen de la transformación lineal definida. El núcleo se muestra como un arreglo vacío si no hay vectores en el espacio nulo de la matriz (es decir, si todos los valores singulares son no nulos). La imagen se muestra en términos de los vectores base de su espacio.


### Sugerencias para Ejercicios Adicionales

1. **Experimentar con Diferentes Transformaciones:** Modifique la función \( T \) para explorar cómo cambian el núcleo y la imagen con diferentes transformaciones lineales.
2. **Explorar con Otras Bases:** Cambie la base utilizada para ver cómo la representación matricial de \( T \), y por tanto su núcleo y imagen, dependen de la elección de la base.
3. **Dimensiones Superiores:** Amplíe este marco de trabajo para transformaciones lineales en espacios de dimensiones superiores para explorar la complejidad añadida que esto conlleva.

# Actividad 2.8: Transformaciones Lineales en Espacios de Polinomios

En este ejercicio, nos enfocaremos en las transformaciones lineales en el espacio de polinomios. Un espacio de polinomios es un conjunto de polinomios que forma un espacio vectorial. Por ejemplo, el conjunto de todos los polinomios de grado menor o igual a \( n \) con coeficientes reales forma un espacio vectorial.

La transformación que exploraremos es la derivada de un polinomio. La derivada de un polinomio es otra función polinómica y, como veremos, esta operación es una transformación lineal.

## Objetivos de Aprendizaje

- Comprender qué es una transformación lineal.
- Implementar una transformación lineal específica en el espacio de polinomios.
- Verificar las propiedades de linealidad de la transformación implementada.


In [11]:

import numpy as np

def T_pol(v):
    """
    Realiza la derivada de un polinomio.
    
    Parámetros:
    - v (np.poly1d): Polinomio al que se le aplicará la derivada.
    
    Retorna:
    - np.poly1d: Polinomio resultante después de aplicar la derivada.
    """
    return np.polyder(v)

# Definición de algunos polinomios de ejemplo
polinomios = [
    np.poly1d([1, 2, 3]),  # Representa el polinomio x^2 + 2x + 3
    np.poly1d([4, 5, 6]),  # Representa el polinomio 4x^2 + 5x + 6
    np.poly1d([7, 8, 9])   # Representa el polinomio 7x^2 + 8x + 9
]

# Aplicación de la transformación T a cada polinomio y visualización de resultados
for p in polinomios:
    print("Polinomio original:\n", p, "\n")
    print("Transformación T(p) (derivada):\n", T_pol(p), "\n")
    print("----------")


Polinomio original:
    2
1 x + 2 x + 3 

Transformación T(p) (derivada):
  
2 x + 2 

----------
Polinomio original:
    2
4 x + 5 x + 6 

Transformación T(p) (derivada):
  
8 x + 5 

----------
Polinomio original:
    2
7 x + 8 x + 9 

Transformación T(p) (derivada):
  
14 x + 8 

----------


## Discusión de Resultados

Los resultados muestran las derivadas de los polinomios dados. La derivada de un polinomio reduce el grado del polinomio original por uno y es calculada multiplicando cada coeficiente por su respectivo exponente y reduciendo el exponente por uno. Por ejemplo, la derivada de \(x^2 + 2x + 3\) es \(2x + 2\). 

Esta transformación es lineal porque satisface dos propiedades clave:
1. **Aditividad**: \(T(u + v) = T(u) + T(v)\)
2. **Homogeneidad**: \(T(αu) = αT(u)\)

Podemos realizar un par de verificaciones adicionales para confirmar estas propiedades.

## Sugerencias para Ejercicios Adicionales

1. Extiende la función `T_pol` para que también pueda calcular derivadas de orden superior.
2. Implementa otras transformaciones lineales en el espacio de polinomios, como la integración o la evaluación en un punto dado.
3. Verifica las propiedades de linealidad para las nuevas transformaciones implementadas.


# Actividad 2.9: Verificación de Isomorfismos

Un **isomorfismo** en el contexto del álgebra lineal es una transformación lineal que es a la vez inyectiva y sobreyectiva entre espacios vectoriales, lo que implica que tiene una inversa que también es lineal. Esta propiedad es fundamental porque sugiere que los espacios vectoriales involucrados tienen la misma estructura algebraica, permitiendo la transferencia de problemas y soluciones de un espacio a otro de manera coherente.

Para verificar si una transformación lineal es un isomorfismo, se puede utilizar la representación matricial de la transformación y revisar si la matriz es invertible. Una matriz es invertible si y solo si su rango es igual a su número de filas (o columnas), lo cual es equivalente a decir que su determinante es no nulo.

En esta notebook, implementaremos una función para verificar si una transformación lineal es un isomorfismo usando Python y algunas funciones útiles de la biblioteca `numpy`.

## Teoría

Una transformación lineal $T: V \rightarrow W$ entre dos espacios vectoriales es un isomorfismo si se cumplen las siguientes condiciones:

1. **Inyectividad:** $T(x) = T(y) \Rightarrow x = y$.
2. **Sobreyectividad:** Para todo $w \in W$, existe al menos un $v \in V$ tal que $T(v) = w$.
3. **Linealidad:** $T(ax + by) = aT(x) + bT(y)$ para cualesquiera $x, y \in V$ y escalares $a, b$.

Si $T$ es un isomorfismo, entonces la matriz asociada $A$ a la transformación respecto a las bases de $V$ y $W$ es una matriz cuadrada invertible. Así, verificar si $T$ es un isomorfismo se reduce a verificar si la matriz asociada es invertible.

In [13]:

import numpy as np

def representacion_matricial(T, base):
    # Esta función debe ser implementada para obtener la matriz de la transformación T
    # Supongamos que T es la transformación identidad en R2 para este ejemplo.
    return np.array([
        [1, 0],
        [0, 1]
    ])

def es_isomorfismo(T, base):
    A = representacion_matricial(T, base)
    return np.linalg.matrix_rank(A) == len(base)

base = [
    [2, 0],
    [0, 3]
]

print("¿Es un isomorfismo?", es_isomorfismo(T, base))

¿Es un isomorfismo? True


## Discusión

En el código proporcionado, la función `representacion_matricial` se supone que genera la matriz de la transformación lineal `T`. Para propósitos de demostración, hemos utilizado la matriz identidad, que es trivialmente un isomorfismo en $\mathbb{R}^2$.

Es importante adaptar la función `representacion_matricial` para que acepte cualquier transformación lineal general y calcule correctamente su matriz en la base dada. Esto podría involucrar el cálculo de la acción de `T` sobre cada vector de la base y expresar el resultado como una combinación lineal de los vectores de la base.

## Ejercicios Adicionales

1. Implementar la función `representacion_matricial` para diferentes transformaciones lineales y verificar si son isomorfismos.
2. Modificar la base y observar cómo cambia la matriz de la transformación y su invertibilidad.
3. Explorar el concepto de isomorfismo en espacios de dimensión mayor y con diferentes bases, incluyendo bases no estándares.

Estos ejercicios ayudarán a profundizar la comprensión de los conceptos de transformaciones lineales e isomorfismos en diferentes contextos y dimensiones.

# Laboratorio: Resolución de Problemas para Encontrar Bases y Determinar la Dimensión de Subespacios

Un subespacio es un conjunto de vectores que contiene el vector cero, es cerrado bajo la suma de vectores y bajo la multiplicación por escalares. Determinar las bases y la dimensión de un subespacio es fundamental porque proporciona una manera compacta y eficiente de describir ese espacio.

### Base de un Subespacio
Una base de un subespacio en \(\mathbb{R}^n\) es un conjunto de vectores que son linealmente independientes y que generan completamente el subespacio. La dimensión de este subespacio es simplemente el número de vectores en la base.

### Generadores Mínimos
Un conjunto de generadores mínimos para un subespacio es un conjunto de vectores que generan el subespacio y que es de cardinalidad mínima. Esto significa que eliminando cualquier vector del conjunto, este dejaría de generar todo el subespacio.

### Objetivo del Ejercicio
El objetivo de esta actividad es determinar bases y la dimensión de subespacios definidos por algunas condiciones y verificar si un conjunto dado de vectores en \(\mathbb{R}^3\) forma un conjunto de generadores mínimos.

## Metodología
Para resolver este problema utilizaremos la descomposición QR, que factoriza una matriz \( A \) en el producto de una matriz ortogonal \( Q \) y una matriz triangular superior \( R \). La matriz \( R \) en la descomposición QR nos ayudará a identificar los vectores linealmente independientes y, por lo tanto, a determinar la base del subespacio generado por los vectores dados.

In [14]:

import numpy as np

def encontrar_base(vectores):
    """
    Esta función encuentra una base para el subespacio generado por los vectores dados.
    Utiliza la descomposición QR para determinar los vectores linealmente independientes.
    
    Args:
    vectores (list of lists): Lista de vectores que generan el subespacio.
    
    Returns:
    numpy.ndarray: Una base para el subespacio.
    """
    # Convertir la lista de vectores en una matriz transpuesta
    matriz = np.array(vectores).T
    
    # Realizar la descomposición QR
    q, r = np.linalg.qr(matriz)
    
    # Obtener el rango de la matriz para determinar los vectores independientes
    rango = np.linalg.matrix_rank(matriz)
    
    # La base se compone de las filas no nulas de R
    base = r[:rango, :]
    
    return base.T


# Vectores que generan el subespacio en R^3
vectores = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# Encontrar la base del subespacio
base = encontrar_base(vectores)
print("Base del subespacio:", base)
print("Dimensión del subespacio:", base.shape[0])

# Verificar si los vectores dados forman un conjunto de generadores mínimos
base_minima = encontrar_base(vectores)
print("Generadores mínimos:", base_minima)


Base del subespacio: [[ -3.74165739   0.        ]
 [ -8.55235974   1.96396101]
 [-13.3630621    3.92792202]]
Dimensión del subespacio: 3
Generadores mínimos: [[ -3.74165739   0.        ]
 [ -8.55235974   1.96396101]
 [-13.3630621    3.92792202]]


## Discusión de Resultados

El código anterior determina la base del subespacio generado por un conjunto de vectores en \(\mathbb{R}^3\). Utiliza la descomposición QR para identificar los vectores linealmente independientes y, por lo tanto, determinar la base. La dimensión del subespacio se calcula como el número de vectores en la base.

### Sugerencias para Ejercicios Adicionales
1. Probar el código con diferentes conjuntos de vectores para explorar cómo varían las bases y dimensiones de subespacios.
2. Implementar una función que verifique explícitamente si cada vector en un conjunto es una combinación lineal de los otros, lo cual ayudaría a determinar si el conjunto es un conjunto de generadores mínimos.
3. Explorar la relación entre la descomposición QR y otros métodos de factorización, como la descomposición LU o SVd, en la determinación de bases de subespacios.

# Representación de Vectores en Términos de una Base

Un vector puede ser representado en términos de diferentes bases. Una base de un espacio vectorial es un conjunto de vectores que son linealmente independientes y que pueden combinarse de forma lineal para representar cualquier vector en ese espacio.

### ¿Qué es una Base?

Una base $\mathcal{B} = \{\mathbf{v}_1, \mathbf{v}_2, \dots, \mathbf{v}_n\}$ de un espacio vectorial $V$ es un conjunto de vectores que cumple dos condiciones:

1. **Linealmente Independientes**: Ningún vector en la base puede ser escrito como una combinación lineal de los otros vectores en la base.
2. **Spanning**: Cualquier vector en el espacio vectorial $V$ puede ser expresado como una combinación lineal de los vectores en la base.

### Coordenadas de un Vector

Cuando expresamos un vector en términos de una base, lo que estamos haciendo es encontrar los coeficientes (o coordenadas) que multiplicados por los vectores de la base y sumados dan como resultado el vector original. Estas coordenadas se denominan **coordenadas del vector respecto a la base**.

### Objetivo del Ejercicio

El objetivo de este ejercicio es representar un vector dado en términos de una base específica. Utilizaremos la biblioteca `numpy` de Python para resolver un sistema de ecuaciones lineales que nos permitirá encontrar las coordenadas del vector en la base dada.

## Ejemplo Práctico



In [15]:
import numpy as np

# Definir la base
base = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 2]
]

# Definir el vector
vector = [2, 3, 4]

# Resolver el sistema de ecuaciones para encontrar las coordenadas
coordenadas = np.linalg.solve(np.array(base).T, vector)
print("Coordenadas del vector en la base:", coordenadas)


Coordenadas del vector en la base: [2. 3. 2.]



## Explicación del Código

En el código anterior, hemos utilizado la función `np.linalg.solve`, la cual resuelve un sistema de ecuaciones lineales. La matriz `base` representa los vectores de la base en forma de columna, y el `vector` es aquel cuyo las coordenadas deseamos encontrar.

- `np.array(base).T` crea una matriz de numpy y toma su transpuesta, asegurando que los vectores base están dispuestos en columnas.
- `vector` es convertido en un array de numpy automáticamente al pasar por `np.linalg.solve`.

El resultado, `coordenadas`, es un array que contiene las coordenadas del `vector` expresado en la base dada.

## Conclusiones y Ejercicios Adicionales

Este ejercicio nos muestra cómo transformar las coordenadas de un vector a una nueva base utilizando operaciones matemáticas y funciones de `numpy`. Este tipo de operaciones son fundamentales en áreas como gráficos por computadora, física, ingeniería y más.

### Ejercicios para Practicar

1. Cambia la base y el vector y observa cómo cambian las coordenadas resultantes.
2. Intenta representar un vector en un espacio de menor dimensión y discute qué sucede.
3. Explica qué pasaría si la base no es ortogonal y cómo afectaría al resultado.

Estos ejercicios ayudarán a profundizar tu comprensión sobre cómo los vectores pueden ser expresados en diferentes bases y la importancia de la elección de una base adecuada en diferentes aplicaciones prácticas.


# No-Unicidad de las Bases en Espacios Vectoriales

 Una base de un espacio vectorial \( V \) es un conjunto de vectores en \( V \) que son linealmente independientes y que generan todo el espacio \( V \). Esto significa que cualquier vector en \( V \) puede ser expresado de manera única como una combinación lineal de los vectores de la base.

 ### Propiedad de No-Unicidad

 Una de las propiedades clave de las bases es su **no-unicidad**. Para un espacio vectorial dado, puede haber muchas selecciones diferentes de conjuntos de vectores que pueden servir como una base. Esta propiedad es crucial porque nos permite elegir una base que sea más conveniente para un problema particular. Por ejemplo, en el procesamiento de señales y en la compresión de datos, elegir una base que simplifique los cálculos o que minimice el error es de gran importancia práctica.

 ### Ejemplos de Bases en \( \mathbb{R}^3 \)

 Consideremos el espacio \( \mathbb{R}^3 \). Un ejemplo de base estándar es \(\{ (1, 0, 0), (0, 1, 0), (0, 0, 1) \}\). Sin embargo, cualquier conjunto de tres vectores linealmente independientes en \( \mathbb{R}^3 \) también formará una base. Esto puede incluir conjuntos de vectores que no son ortogonales ni normalizados.

 ### Objetivos del Notebook

 En este notebook, implementaremos una función para extraer una base de un conjunto de vectores y demostraremos con ejemplos cómo diferentes conjuntos de vectores (que son linealmente independientes) pueden formar bases distintas para el mismo espacio vectorial. Discutiremos la aplicación de este concepto y cómo puede ser útil en diferentes contextos como la reducción de dimensionalidad mediante PCA (Análisis de Componentes Principales) y ICA (Análisis de Componentes Independientes).

In [16]:

import numpy as np

def encontrar_bases(vectores):
    """
    Esta función encuentra una base para el conjunto de vectores dado utilizando la descomposición QR.
    
    Parámetros:
        vectores (list): Lista de vectores que representan el conjunto para el cual se busca la base.
        
    Retorna:
        numpy.ndarray: Una base para el espacio generado por los vectores.
    """
    matriz = np.array(vectores).T
    q, r = np.linalg.qr(matriz)
    base = r[:np.linalg.matrix_rank(matriz)]
    return base.T


# Definimos un conjunto de vectores que forman una base estándar en R^3
vectores = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
]


base1 = encontrar_bases(vectores)
print("Primera base (base estándar):", base1)

# Definimos un segundo conjunto de vectores que también son linealmente independientes
vectores_alternativos = [
    [1, 1, 0],
    [0, 1, 1],
    [1, 0, 1]
]

base2 = encontrar_bases(vectores_alternativos)
print("Segunda base (alternativa):", base2)


Primera base (base estándar): [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Segunda base (alternativa): [[-1.41421356  0.          0.        ]
 [-0.70710678 -1.22474487  0.        ]
 [-0.70710678 -0.40824829  1.15470054]]


## Discusión

Como se observa en los resultados de las celdas de código anteriores, hemos encontrado dos bases diferentes para \( \mathbb{R}^3 \). La primera base es la base estándar, mientras que la segunda es una base alternativa formada por vectores que no son ortogonales ni normalizados. Ambos conjuntos son bases válidas porque cada uno puede generar todo el espacio \( \mathbb{R}^3 \) y los vectores son linealmente independientes en cada conjunto.

### Importancia de la No-Unicidad

La no-unicidad de las bases es fundamental en muchas aplicaciones. En análisis de datos, por ejemplo, diferentes bases pueden proporcionar diferentes perspectivas sobre los datos. En algoritmos como PCA y ICA, elegir una base que maximice la varianza explicada o que haga que las componentes sean estadísticamente independientes puede revelar estructuras subyacentes en los datos que no son aparentes en la base estándar.

### Ejercicios Sugeridos

1. Implementa una función que determine si un conjunto dado de vectores es una base de \( \mathbb{R}^3 \).
2. Explora el efecto de cambiar las bases en la interpretación de los datos en un conjunto de datos simple usando PCA.
3. Investiga cómo diferentes bases afectan la solución de sistemas de ecuaciones lineales.

La exploración de estos ejercicios proporcionará una comprensión más profunda de cómo la elección de una base puede afectar la solución de problemas prácticos.