# [Numpy](https://numpy.org/doc/stable/index.html)



In [1]:
import numpy as np

Tipos de numpy

In [2]:
np.bool_, np.byte, np.ubyte, np.short, np.ushort, np.intc, np.uintc, np.int_, np.uint, np.longlong, np.ulonglong, np.half, np.float16, np.single, np.double, np.longdouble, np.csingle, np.cdouble, np.clongdouble

(numpy.bool_,
 numpy.int8,
 numpy.uint8,
 numpy.int16,
 numpy.uint16,
 numpy.int32,
 numpy.uint32,
 numpy.int64,
 numpy.uint64,
 numpy.longlong,
 numpy.ulonglong,
 numpy.float16,
 numpy.float16,
 numpy.float32,
 numpy.float64,
 numpy.float128,
 numpy.complex64,
 numpy.complex128,
 numpy.complex256)

## [Arrays](https://numpy.org/doc/stable/reference/arrays.html)

Los arrays son el tipo de datos más importante que provee NumPy. En su versión más básica representan vectores pero pueden tener más dimensiones y representar matrices y tensores en general.

El tipo se llama ndarray pero también se lo conoce en la librería simplemente como array.

En su versión más simple podemos pensar que no es más que una lista de python pero:

* A diferencia de las listas en python, solo pueden tener un tipo de datos adentro.
* Existen un montón de operaciones matemáticas definidas y optimizadas para trabajar con este tipo de datos.

Al ser una clase de python, además de métodos tiene atributos. Veamos algunos de ellos

In [3]:
an_array = np.arange(20)
an_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
an_array.shape

(20,)

In [5]:
an_array.ndim

1

In [6]:
an_array.size

20

In [7]:
an_array.dtype

dtype('int64')

### [Armando arrays](https://numpy.org/doc/stable/user/basics.creation.html)

Por un lado, tenemos el constructor de la clase que admite como parámetro listas de valores. Por otro lado, existen diversas funciones que crean arrays. Veamos algunas.

In [8]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [9]:
np.arange(10,30,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [10]:
np.linspace(0.1,0.5,4)

array([0.1       , 0.23333333, 0.36666667, 0.5       ])

In [11]:
np.logspace(1,10,10)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [12]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.random.rand(3,2) # random entre 0 y 1

array([[0.97089891, 0.48918971],
       [0.9935421 , 0.02775979],
       [0.23161978, 0.06222531]])

In [15]:
np.random.randint(1,10,(3,2)) # enteros random entre [1 y 10)

array([[6, 7],
       [9, 8],
       [4, 3]])

In [16]:
np.random.standard_normal((8,2))

array([[-0.357811  ,  0.7205878 ],
       [ 1.35559227, -0.92366493],
       [ 2.08245792,  0.07183823],
       [ 0.21232088, -0.64619573],
       [ 0.55452519, -1.82501112],
       [-0.83844983,  1.20305603],
       [-1.865581  ,  0.60531625],
       [-1.93579269,  0.76160475]])

Propiedades de un arreglo

In [17]:
an_array = np.ones((2,3))
print('dimensiones: ', an_array.shape)
print('cantidad de dimensiones: ', an_array.ndim)
print('cantidad de elementos: ', an_array.size)
print('tipo: ', an_array.dtype)

dimensiones:  (2, 3)
cantidad de dimensiones:  2
cantidad de elementos:  6
tipo:  float64


Se puede cambiar el tipo de un array

In [18]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [19]:
np.arange(0,10,0.5).astype(np.int32)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9],
      dtype=int32)

## Matrices

Las matrices no son más que array con 2 dimensiones. Si bien existe un tipo específico para matrices en numpy cayó en desuso (y obsolescencia).

In [20]:
a_matrix = np.array([[ 0,  1,  2,  3],
                    [ 4,  5,  6,  7],
                    [ 8,  9, 10, 11],
                    [12, 13, 14, 15]])
a_matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
print(a_matrix.shape, a_matrix.ndim, a_matrix.size, a_matrix.dtype)

(4, 4) 2 16 int64


### Matrices especiales

In [22]:
np.eye(3) # Identidad de 3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.diag([77,90]) # Matriz diagonal

array([[77,  0],
       [ 0, 90]])

In [24]:
np.diag(np.ones(3),1) # Superdiagonal 1

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [25]:
np.vander(np.arange(4),increasing=True) # Matriz de Vandermonde (veremos al final de la materia qué significa)

array([[ 1,  0,  0,  0],
       [ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27]])

## Cambio de dimensiones

Algunos métodos que modifican las dimensiones:
* reshape: Devuelve un nuevo array con las dimensiones indicadas como
parámetro. Si alguno de los parámetros es igual a -1, se calculan las
dimensiones para que sea factible el cambio.

* resize: el mismo efecto que “reshape” pero modifica el array en vez de devolver
uno nuevo.

* T: sirve para transponer una matriz.

* ravel, flattened: “aplana” el array devolviendo todo en una sola dimensión.

In [26]:
a_matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
a_matrix.reshape(1,16)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [28]:
a_matrix.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [29]:
a_matrix.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
a_matrix.resize(1,16)
a_matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

## Operaciones con arrays

Existen muchísimas operaciones definidas para arrays.

### Operadores básicos

Los operadores básicos de sumas, restas, potencias, etc se encuentran sobrecargados.

In [31]:
v = np.arange(1,7)
w = np.ones(6)
v, w

(array([1, 2, 3, 4, 5, 6]), array([1., 1., 1., 1., 1., 1.]))

In [32]:
v + w

array([2., 3., 4., 5., 6., 7.])

In [33]:
v > w

array([False,  True,  True,  True,  True,  True])

In [34]:
v - w

array([0., 1., 2., 3., 4., 5.])

In [35]:
v ** 2

array([ 1,  4,  9, 16, 25, 36])

In [36]:
np.sqrt(v)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [37]:
print(np.sin(v), "\n", np.cos(v), "\n", np.floor(np.cos(v)), "\n", np.round(np.cos(v)))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ] 
 [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029] 
 [ 0. -1. -1. -1.  0.  0.] 
 [ 1. -0. -1. -1.  0.  1.]


### Operaciones entre vectores

In [38]:
np.dot(v,w) #Producto iterno (o escalar)

21.0

In [39]:
np.outer(v,w) #Producto externo

array([[1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6.]])

### Multiplicación de matrices

Existe la multiplicación clásica entre matrices (con
el símbolo @) o el producto elemento a elemento (producto Hadamard)

In [40]:
M1 = np.arange(1,10).reshape(3,3)
M2 = np.ones((3,3))
M1, M2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [41]:
M1 * M2 #Producto Hadamard o elemento a elemento

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [42]:
np.matmul(M1,M2) #Producto interno de matrices

array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [24., 24., 24.]])

In [43]:
M1 @ M2 #Producto interno de matrices

array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [24., 24., 24.]])

**EJERCICIO**: Multiplicar $M_{1}v$ siendo $v = (1,1,1)$ como columna

In [44]:
...

Ellipsis

## [Indexación de arreglos](https://numpy.org/doc/stable/user/basics.indexing.html)

Los arrays en NumPy se pueden acceder a posiciones particulares o mediante 'slicing' de maneras parecidas a las listas nativas. Observar los siguientes comandos e interpretar.

In [45]:
an_array = np.arange(0,40,2)
an_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [46]:
an_array[6]

12

In [47]:
start = 2
end = 18
step = 2

an_array[start:end:step]

array([ 4,  8, 12, 16, 20, 24, 28, 32])

In [48]:
# Son equivalentes
#an_array[0:end:]
#an_array[:end:]
an_array[:end]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34])

In [49]:
an_array[:-1]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36])

In [50]:
an_array[::]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [51]:
an_array[::-1]

array([38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10,  8,  6,
        4,  2,  0])

In [52]:
for element in an_array[:5]:
    print(element)

0
2
4
6
8


In [53]:
a_matrix = np.arange(16).reshape((4,4))
a_matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
a_matrix[:,2]

array([ 2,  6, 10, 14])

In [55]:
a_matrix[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [56]:
a_matrix[-1,:]

array([12, 13, 14, 15])

In [57]:
for row in a_matrix:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]


In [58]:
a_matrix[1:3,2:4]

array([[ 6,  7],
       [10, 11]])

## Máscaras

Es posible seleccionar elementos de un arreglo utilizando como índice otro arreglo de booleanos. Esto es mucho más eficiente que realizar un ciclo que recorra todo el arreglo y ejecute una condición en cada posición.

In [59]:
import time

an_array = np.arange(4)
mask = np.array([False,True,True,False])
an_array[mask]

array([1, 2])

Las operaciones con máscaras son más rápidas que operar elemento a elemento con condiciones

In [60]:
an_array = np.arange(100)
an_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [61]:
np.array([x for x in an_array if x>50])

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [62]:
an_array[an_array>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [63]:
%timeit np.array([x for x in an_array if x>50])

36.2 µs ± 6.71 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [64]:
%timeit an_array[an_array>50]

4.62 µs ± 237 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Tipos de asignación

### Referencia

In [65]:
an_array = np.arange(10)
an_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
another_array = an_array

In [67]:
another_array[3] = 8
an_array

array([0, 1, 2, 8, 4, 5, 6, 7, 8, 9])

### [Vista](https://numpy.org/doc/stable/user/basics.copies.html)

In [68]:
an_array = np.arange(10)
an_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
another_array = an_array.view()

In [70]:
another_array = another_array.reshape((5,2))
another_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [71]:
an_array[3] = 8

In [72]:
another_array

array([[0, 1],
       [2, 8],
       [4, 5],
       [6, 7],
       [8, 9]])

### [Copia](https://numpy.org/doc/stable/user/basics.copies.html)


In [73]:
another_array = np.arange(10)

In [74]:
an_array = another_array.copy()

In [75]:
an_array[3] = 8

In [76]:
an_array, another_array

(array([0, 1, 2, 8, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

## Operaciones matemáticas

In [77]:
np.sum(np.arange(1000)) # suma los elementos de un arreglo

499500

In [78]:
arr = np.arange(16).reshape(4,4,)
np.sum(arr,0) #  de un arreglo 2d, suma solo un eje, el 0, el primero

array([24, 28, 32, 36])

In [79]:
np.diff(np.arange(10)) # resta elementos consecutivos

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [80]:
np.cumsum(np.arange(10)) # suma acumulada

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

## Álgebra Lineal

Numpy utiliza BLAS y LAPACK para las operaciones de álgebra lineal

https://numpy.org/doc/stable/reference/routines.linalg.html#module-numpy.linalg

Descomposiciones, autovalores, normas, determinante, rango, sistemas de ecuaciones, inversa, ...

In [81]:
import numpy.linalg as lng

In [82]:
A = np.random.randint(1,10,(3,3))
A

array([[1, 4, 2],
       [1, 4, 3],
       [6, 6, 2]])

In [83]:
lng.inv(A)  # Inversa

array([[-0.55555556,  0.22222222,  0.22222222],
       [ 0.88888889, -0.55555556, -0.05555556],
       [-1.        ,  1.        , -0.        ]])

In [84]:
lng.det(A)  # Determinante

17.999999999999996

## Resolver sistemas de ecuaciones

In [85]:
A = np.random.randint(-9,10,(4,4))
x = np.random.randint(-9,10,(4,1))
b = A@x
A, x, b

(array([[-5,  9,  4,  1],
        [ 7,  8, -7,  0],
        [-6, -3,  9,  9],
        [-5,  5,  7,  3]]),
 array([[ 3],
        [-8],
        [-4],
        [ 0]]),
 array([[-103],
        [ -15],
        [ -30],
        [ -83]]))

In [86]:
x_solve = lng.solve(A,b)
print(x_solve)
np.allclose(x,x_solve)

[[ 3.]
 [-8.]
 [-4.]
 [-0.]]


True

## Ejercicios

Realizar el ejercicio 3 de la práctica 1, ejecutando los comandos indicados.

Realizar el ejercicio 21 de la Práctica 1. Utilizar ejercicio21_P1.py, completarlo y ejecutarlo en Spyder. Si surgen errores, hacer debugging en Spyder.

Realizar el ejercicio 4 de la práctica 1.